	Computer_System u0 (
		.audio_ADCDAT                                    (<connected-to-audio_ADCDAT>),                                    //                               audio.ADCDAT
		.audio_ADCLRCK                                   (<connected-to-audio_ADCLRCK>),                                   //                                    .ADCLRCK
		.audio_BCLK                                      (<connected-to-audio_BCLK>),                                      //                                    .BCLK
		.audio_DACDAT                                    (<connected-to-audio_DACDAT>),                                    //                                    .DACDAT
		.audio_DACLRCK                                   (<connected-to-audio_DACLRCK>),                                   //                                    .DACLRCK
		.audio_clk_clk                                   (<connected-to-audio_clk_clk>),                                   //                           audio_clk.clk
		.audio_pll_ref_clk_clk                           (<connected-to-audio_pll_ref_clk_clk>),                           //                   audio_pll_ref_clk.clk
		.audio_pll_ref_reset_reset                       (<connected-to-audio_pll_ref_reset_reset>),                       //                 audio_pll_ref_reset.reset
		.av_config_SDAT                                  (<connected-to-av_config_SDAT>),                                  //                           av_config.SDAT
		.av_config_SCLK                                  (<connected-to-av_config_SCLK>),                                  //                                    .SCLK
		.bus_master_audio_external_interface_address     (<connected-to-bus_master_audio_external_interface_address>),     // bus_master_audio_external_interface.address
		.bus_master_audio_external_interface_byte_enable (<connected-to-bus_master_audio_external_interface_byte_enable>), //                                    .byte_enable
		.bus_master_audio_external_interface_read        (<connected-to-bus_master_audio_external_interface_read>),        //                                    .read
		.bus_master_audio_external_interface_write       (<connected-to-bus_master_audio_external_interface_write>),       //                                    .write
		.bus_master_audio_external_interface_write_data  (<connected-to-bus_master_audio_external_interface_write_data>),  //                                    .write_data
		.bus_master_audio_external_interface_acknowledge (<connected-to-bus_master_audio_external_interface_acknowledge>), //                                    .acknowledge
		.bus_master_audio_external_interface_read_data   (<connected-to-bus_master_audio_external_interface_read_data>),   //                                    .read_data
		.collide_finish_export                           (<connected-to-collide_finish_export>),                           //                      collide_finish.export
		.ux_in_export                                    (<connected-to-ux_in_export>),                                    //                               ux_in.export
		.uy_in_export                                    (<connected-to-uy_in_export>),                                    //                               uy_in.export
		.hps_io_hps_io_emac1_inst_TX_CLK                 (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),                 //                              hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0                   (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),                   //                                    .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1                   (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),                   //                                    .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2                   (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),                   //                                    .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3                   (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),                   //                                    .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0                   (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),                   //                                    .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO                   (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),                   //                                    .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC                    (<connected-to-hps_io_hps_io_emac1_inst_MDC>),                    //                                    .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL                 (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),                 //                                    .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL                 (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),                 //                                    .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK                 (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),                 //                                    .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1                   (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),                   //                                    .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2                   (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),                   //                                    .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3                   (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),                   //                                    .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0                     (<connected-to-hps_io_hps_io_qspi_inst_IO0>),                     //                                    .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1                     (<connected-to-hps_io_hps_io_qspi_inst_IO1>),                     //                                    .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2                     (<connected-to-hps_io_hps_io_qspi_inst_IO2>),                     //                                    .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3                     (<connected-to-hps_io_hps_io_qspi_inst_IO3>),                     //                                    .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0                     (<connected-to-hps_io_hps_io_qspi_inst_SS0>),                     //                                    .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK                     (<connected-to-hps_io_hps_io_qspi_inst_CLK>),                     //                                    .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD                     (<connected-to-hps_io_hps_io_sdio_inst_CMD>),                     //                                    .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0                      (<connected-to-hps_io_hps_io_sdio_inst_D0>),                      //                                    .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1                      (<connected-to-hps_io_hps_io_sdio_inst_D1>),                      //                                    .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK                     (<connected-to-hps_io_hps_io_sdio_inst_CLK>),                     //                                    .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2                      (<connected-to-hps_io_hps_io_sdio_inst_D2>),                      //                                    .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3                      (<connected-to-hps_io_hps_io_sdio_inst_D3>),                      //                                    .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0                      (<connected-to-hps_io_hps_io_usb1_inst_D0>),                      //                                    .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1                      (<connected-to-hps_io_hps_io_usb1_inst_D1>),                      //                                    .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2                      (<connected-to-hps_io_hps_io_usb1_inst_D2>),                      //                                    .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3                      (<connected-to-hps_io_hps_io_usb1_inst_D3>),                      //                                    .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4                      (<connected-to-hps_io_hps_io_usb1_inst_D4>),                      //                                    .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5                      (<connected-to-hps_io_hps_io_usb1_inst_D5>),                      //                                    .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6                      (<connected-to-hps_io_hps_io_usb1_inst_D6>),                      //                                    .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7                      (<connected-to-hps_io_hps_io_usb1_inst_D7>),                      //                                    .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK                     (<connected-to-hps_io_hps_io_usb1_inst_CLK>),                     //                                    .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP                     (<connected-to-hps_io_hps_io_usb1_inst_STP>),                     //                                    .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR                     (<connected-to-hps_io_hps_io_usb1_inst_DIR>),                     //                                    .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT                     (<connected-to-hps_io_hps_io_usb1_inst_NXT>),                     //                                    .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK                    (<connected-to-hps_io_hps_io_spim1_inst_CLK>),                    //                                    .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI                   (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),                   //                                    .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO                   (<connected-to-hps_io_hps_io_spim1_inst_MISO>),                   //                                    .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0                    (<connected-to-hps_io_hps_io_spim1_inst_SS0>),                    //                                    .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX                     (<connected-to-hps_io_hps_io_uart0_inst_RX>),                     //                                    .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX                     (<connected-to-hps_io_hps_io_uart0_inst_TX>),                     //                                    .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA                     (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),                     //                                    .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL                     (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),                     //                                    .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA                     (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),                     //                                    .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL                     (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),                     //                                    .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_gpio_inst_GPIO09                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),                  //                                    .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),                  //                                    .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),                  //                                    .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO41                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO41>),                  //                                    .hps_io_gpio_inst_GPIO41
		.hps_io_hps_io_gpio_inst_GPIO48                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),                  //                                    .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO53                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),                  //                                    .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),                  //                                    .hps_io_gpio_inst_GPIO54
		.hps_io_hps_io_gpio_inst_GPIO61                  (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),                  //                                    .hps_io_gpio_inst_GPIO61
		.init_finish_export                              (<connected-to-init_finish_export>),                              //                         init_finish.export
		.init_ship_export                                (<connected-to-init_ship_export>),                                //                           init_ship.export
		.memory_mem_a                                    (<connected-to-memory_mem_a>),                                    //                              memory.mem_a
		.memory_mem_ba                                   (<connected-to-memory_mem_ba>),                                   //                                    .mem_ba
		.memory_mem_ck                                   (<connected-to-memory_mem_ck>),                                   //                                    .mem_ck
		.memory_mem_ck_n                                 (<connected-to-memory_mem_ck_n>),                                 //                                    .mem_ck_n
		.memory_mem_cke                                  (<connected-to-memory_mem_cke>),                                  //                                    .mem_cke
		.memory_mem_cs_n                                 (<connected-to-memory_mem_cs_n>),                                 //                                    .mem_cs_n
		.memory_mem_ras_n                                (<connected-to-memory_mem_ras_n>),                                //                                    .mem_ras_n
		.memory_mem_cas_n                                (<connected-to-memory_mem_cas_n>),                                //                                    .mem_cas_n
		.memory_mem_we_n                                 (<connected-to-memory_mem_we_n>),                                 //                                    .mem_we_n
		.memory_mem_reset_n                              (<connected-to-memory_mem_reset_n>),                              //                                    .mem_reset_n
		.memory_mem_dq                                   (<connected-to-memory_mem_dq>),                                   //                                    .mem_dq
		.memory_mem_dqs                                  (<connected-to-memory_mem_dqs>),                                  //                                    .mem_dqs
		.memory_mem_dqs_n                                (<connected-to-memory_mem_dqs_n>),                                //                                    .mem_dqs_n
		.memory_mem_odt                                  (<connected-to-memory_mem_odt>),                                  //                                    .mem_odt
		.memory_mem_dm                                   (<connected-to-memory_mem_dm>),                                   //                                    .mem_dm
		.memory_oct_rzqin                                (<connected-to-memory_oct_rzqin>),                                //                                    .oct_rzqin
		.move_trace_finish_export                        (<connected-to-move_trace_finish_export>),                        //                   move_trace_finish.export
		.n0_from_hps_export                              (<connected-to-n0_from_hps_export>),                              //                         n0_from_hps.export
		.ne_from_hps_export                              (<connected-to-ne_from_hps_export>),                              //                         ne_from_hps.export
		.nn_from_hps_export                              (<connected-to-nn_from_hps_export>),                              //                         nn_from_hps.export
		.nne_from_hps_export                             (<connected-to-nne_from_hps_export>),                             //                        nne_from_hps.export
		.nnw_from_hps_export                             (<connected-to-nnw_from_hps_export>),                             //                        nnw_from_hps.export
		.ns_from_hps_export                              (<connected-to-ns_from_hps_export>),                              //                         ns_from_hps.export
		.nse_from_hps_export                             (<connected-to-nse_from_hps_export>),                             //                        nse_from_hps.export
		.nsw_from_hps_export                             (<connected-to-nsw_from_hps_export>),                             //                        nsw_from_hps.export
		.nw_from_hps_export                              (<connected-to-nw_from_hps_export>),                              //                         nw_from_hps.export
		.pipes_export                                    (<connected-to-pipes_export>),                                    //                               pipes.export
		.print_finish_export                             (<connected-to-print_finish_export>),                             //                        print_finish.export
		.reset_lb_export                                 (<connected-to-reset_lb_export>),                                 //                            reset_lb.export
		.sdram_clk_clk                                   (<connected-to-sdram_clk_clk>),                                   //                           sdram_clk.clk
		.ship_x_export                                   (<connected-to-ship_x_export>),                                   //                              ship_x.export
		.ship_y_export                                   (<connected-to-ship_y_export>),                                   //                              ship_y.export
		.speed_color_finish_export                       (<connected-to-speed_color_finish_export>),                       //                  speed_color_finish.export
		.start_collide_export                            (<connected-to-start_collide_export>),                            //                       start_collide.export
		.start_init_export                               (<connected-to-start_init_export>),                               //                          start_init.export
		.start_move_trace_export                         (<connected-to-start_move_trace_export>),                         //                    start_move_trace.export
		.start_print_export                              (<connected-to-start_print_export>),                              //                         start_print.export
		.start_speed_color_export                        (<connected-to-start_speed_color_export>),                        //                   start_speed_color.export
		.start_stream_export                             (<connected-to-start_stream_export>),                             //                        start_stream.export
		.stream_finish_export                            (<connected-to-stream_finish_export>),                            //                       stream_finish.export
		.system_pll_ref_clk_clk                          (<connected-to-system_pll_ref_clk_clk>),                          //                  system_pll_ref_clk.clk
		.system_pll_ref_reset_reset                      (<connected-to-system_pll_ref_reset_reset>),                      //                system_pll_ref_reset.reset
		.test_data_export                                (<connected-to-test_data_export>),                                //                           test_data.export
		.ux_from_hps_export                              (<connected-to-ux_from_hps_export>),                              //                         ux_from_hps.export
		.uy_from_hps_export                              (<connected-to-uy_from_hps_export>),                              //                         uy_from_hps.export
		.write_address_init_export                       (<connected-to-write_address_init_export>),                       //                  write_address_init.export
		.x_fish1_export                                  (<connected-to-x_fish1_export>),                                  //                             x_fish1.export
		.x_fish2_export                                  (<connected-to-x_fish2_export>),                                  //                             x_fish2.export
		.y_fish1_export                                  (<connected-to-y_fish1_export>),                                  //                             y_fish1.export
		.y_fish2_export                                  (<connected-to-y_fish2_export>)                                   //                             y_fish2.export
	);

